"""fix Invite model

Revision ID: 3a812257add8
Revises: 9ce38ff62ed4
Create Date: 2024-04-18 11:20:21.303125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a812257add8'
down_revision: Union[str, None] = '9ce38ff62ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('email', sa.String(length=256), nullable=False))
    op.drop_column('invite', 'account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('account', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('invite', 'email')
    # ### end Alembic commands ###
