"""fix User model

Revision ID: 6d5157cbd0c0
Revises: 3a812257add8
Create Date: 2024-04-18 12:23:20.922355

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d5157cbd0c0"
down_revision: Union[str, None] = "3a812257add8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_position")
    op.drop_table("user_account")
    op.drop_table("user_company")
    op.add_column("user", sa.Column("email", sa.INTEGER(), nullable=False))
    op.add_column("user", sa.Column("company_id", sa.INTEGER(), nullable=False))
    op.add_column("user", sa.Column("position_id", sa.INTEGER(), nullable=False))
    op.create_unique_constraint(None, "user", ["email"])
    op.create_foreign_key(None, "user", "position", ["position_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "user", "company", ["company_id"], ["id"], ondelete="CASCADE")
    op.drop_column("user", "account")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("account", sa.VARCHAR(length=256), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "position_id")
    op.drop_column("user", "company_id")
    op.drop_column("user", "email")
    op.create_table(
        "user_company",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name="user_company_company_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_company_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "company_id", name="user_company_pkey"),
    )
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["account.id"], name="user_account_account_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_account_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "account_id", name="user_account_pkey"),
    )
    op.create_table(
        "user_position",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("position_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
            name="user_position_position_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_position_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "position_id", name="user_position_pkey"),
    )
    # ### end Alembic commands ###
