"""fix fields and

Revision ID: 8f446c28f062
Revises: 21814916d4f2
Create Date: 2024-04-17 19:31:26.872390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f446c28f062'
down_revision: Union[str, None] = '21814916d4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_name', sa.String(length=256), nullable=False))
    op.drop_column('account', 'account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('account', 'account_name')
    # ### end Alembic commands ###
