"""fix Account model

Revision ID: 9ce38ff62ed4
Revises: 8f446c28f062
Create Date: 2024-04-18 11:12:47.189716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce38ff62ed4'
down_revision: Union[str, None] = '8f446c28f062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.String(length=256), nullable=False))
    op.drop_column('account', 'account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('account', 'email')
    # ### end Alembic commands ###
