"""add Role model

Revision ID: a92222dd9339
Revises: 6d5157cbd0c0
Create Date: 2024-04-18 16:52:40.956970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92222dd9339'
down_revision: Union[str, None] = '6d5157cbd0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'guest', name='rolename'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=256),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'hashed_password')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    op.drop_table('role')
    # ### end Alembic commands ###
